apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: kafka-handler
  name: kafka-handler
  namespace: upper-funnel-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-handler
  template:
    metadata:
      labels:
        app: kafka-handler
    spec:
      containers:
        - name: kafka-handler
          env:
            - name: KAFKA_HOST
              value: "kafka-dev.888holdings.corp:9101,kafka-dev.888holdings.corp:9102kafka-dev.888holdings.corp:9103"
            - name: KAFKA_SASL_MECHANISM
              value: "plain"
            - name: KAFKA_SASL_USER
              value: "admin"
            - name: KAFKA_SASL_PASSWORD
              value: "test1234"
            - name: KAFKA_SSL_CERT_LOCATION
              value: "assets/client.truststore.jks"
          ports:
          - containerPort: 3000
            name: http
          image: docker.af.888holdings.corp/upper-funnel/tools/kafka-handler:latest
          imagePullPolicy: Always
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-handler
  namespace: upper-funnel-qa
  labels:
    app: kafka-handler
spec:
  selector:
    app: kafka-handler
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    name: http
